apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {appName}-deployment-{branch}
spec:
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {appName}-{branch}
    spec:
      containers:
      - name: {appName}-{branch}
        image: gcr.io/pass-223419/{appName}-homolog:{version}
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 15
        env:
          - name: JAVA_OPTS
            value: -Dspring.profiles.active=homolog
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-{appName}-{branch}
                key: MONGO_USERNAME 

        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080